# This workflow builds and tests the project

name: test
on: push
env:
  # Specifies dotnet SDK Version
  DOTNET_VERSION: '6.0.x'

jobs:
  ci:
    name: test-job
    runs-on: ubuntu-latest
    
    permissions: write-all

    steps:
    # Checks out the source code at the latest commit
    - uses: actions/checkout@v3
    
    - name: Test Step
      run: bash ".github/workflows/test.sh"
      
    - name: Confirm Test
      shell: bash
      run: echo "Another Test= ${{ env.MyTestVar }}", ${{ env.MyTestVar2 }}"
    
    # Installs the .NET SDK on the build machine
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    # Installs any NuGet packages required.
    - name: Install dependencies
      run: dotnet restore
      
    # Builds the project
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    # Runs any tests in the project
    - name: Test
      run: dotnet test --configuration Release --no-restore --verbosity normal
